<script>
const slides=document.querySelectorAll(".slide");
let current=0;

function go(n){
slides[current].classList.remove("active");
current=n-1;
slides[current].classList.add("active");
}

const noBtn=document.getElementById("noBtn");
noBtn.addEventListener("mouseover",moveNo);

function moveNo(){
noBtn.style.left=Math.random()*80+"%";
noBtn.style.top=Math.random()*80+"%";
}

const music=document.getElementById("bgMusic");
document.body.addEventListener("click",()=>music.play(),{once:true});

for(let i=0;i<25;i++){
let h=document.createElement("div");
h.className="heart";
h.innerHTML="❤️";
h.style.left=Math.random()*100+"%";
h.style.animationDuration=4+Math.random()*6+"s";
document.body.appendChild(h);
}
</script>
 
